sudo: required
services:
  - docker

before_install:
  - docker build -t svet93/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true svet93/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-west-2"
  app: "react-docker"
  env: "ReactDocker-env"
  bucket_name: "elasticbeanstalk-us-west-2-791925802913"
  bucket_path: "react-docker"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY